version: '3.8'

services:
  pointcloud-processor:
    build: .
    container_name: pointcloud_app
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    stdin_open: true
    tty: true

