version: '3.8'

services:
  pointcloud-processor:
    build: .
    container_name: pointcloud_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    working_dir: /app
    stdin_open: true
    tty: true

